In [1]:
import numpy as np
arr = np.array([])
print(arr)
print(type(arr))

[]
<class 'numpy.ndarray'>


In [2]:
print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions (an empty array has number of dimensions equals to 1)
print("arr.shape: ", arr.shape) # This is an empty array, so have a shape of (0, )
print("arr.size: ", arr.size)   # get total number of elements
print("arr.dtype: ", arr.dtype) # get data type, default for empty array is float64
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array default is 8 for float64
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory

print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array:  []
arr.ndim:  1
arr.shape:  (0,)
arr.size:  0
arr.dtype:  float64
arr.itemsize:  8
arr.nbytes:  0
arr.data:  <memory at 0x000001F88B613D00>
arr.strides:  (0,)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [3]:
x = np.array(42)  # just a number
print(x)
print("Shape:", x.shape)
print("Dimension (ndim):", x.ndim)

42
Shape: ()
Dimension (ndim): 0


In [4]:
# Create a 0-D numpy array using array() constructor
import numpy as np
arr = np.array([1,5,9,10])
print("array: ", arr)

array:  [ 1  5  9 10]


In [5]:
print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions (a 0-D array has number of dimensions equals to 0)
print("arr.shape: ", arr.shape) # This is a scalar value, so have no shape ( )
print("arr.size: ", arr.size)   # get total number of elements, in this case it is 1
print("arr.dtype: ", arr.dtype) # get data type, default is what is minimum required to hold the only element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array default is 8 for int64
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory

print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array:  [ 1  5  9 10]
arr.ndim:  1
arr.shape:  (4,)
arr.size:  4
arr.dtype:  int64
arr.itemsize:  8
arr.nbytes:  32
arr.data:  <memory at 0x000001F88B613D00>
arr.strides:  (8,)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [6]:
arr = np.array([[5,3,2],[8,9,-1],[2,-3,6]])
arr

array([[ 5,  3,  2],
       [ 8,  9, -1],
       [ 2, -3,  6]])

In [7]:
for i in range(3):
    for j in range(3):
        print(arr[i,j])

5
3
2
8
9
-1
2
-3
6


In [8]:
# creating 3-D (5x4x3) array using array constructor in numpy
mylist = [
          [[1, 2, 3], [5, 6, 7], [3, 2, 4], [7, 3, 4]],
          [[8, 1, 6], [1, 9, 4], [5, 6, 4], [2, 6, 2]],
          [[5, 3, 2], [2, 0, 5], [8, 3, 0], [5, 6, 9]],
          [[6, 7, 1], [8, 1, 6], [1, 4, 7], [2, 0, 4]],
          [[2, 8, 9], [3, 0, 4], [5, 2, 2], [1, 3, 8]],
         ]
arr = np.array(mylist, dtype=np.uint8)


print("array: \n", arr)
print("arr.ndim: ", arr.ndim)    # get number of dimensions (3-D array)
print("arr.shape: ", arr.shape)  # get dimension size.For a 3-D array, return a tuple with three elements
print("arr.size: ", arr.size)    # get total number of elements (5*4*3=60 elements)
print("arr.dtype: ", arr.dtype)  # get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (8*60=4800)


print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array: 
 [[[1 2 3]
  [5 6 7]
  [3 2 4]
  [7 3 4]]

 [[8 1 6]
  [1 9 4]
  [5 6 4]
  [2 6 2]]

 [[5 3 2]
  [2 0 5]
  [8 3 0]
  [5 6 9]]

 [[6 7 1]
  [8 1 6]
  [1 4 7]
  [2 0 4]]

 [[2 8 9]
  [3 0 4]
  [5 2 2]
  [1 3 8]]]
arr.ndim:  3
arr.shape:  (5, 4, 3)
arr.size:  60
arr.dtype:  uint8
arr.itemsize:  1
arr.nbytes:  60
arr.data:  <memory at 0x000001F88B5331F0>
arr.strides:  (12, 3, 1)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [9]:
arr = np.zeros(3, dtype=int)
arr

array([0, 0, 0])

In [10]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr = np.zeros((2,3), dtype=np.int16)
arr, arr.nbytes

(array([[0, 0, 0],
        [0, 0, 0]], dtype=int16),
 12)

In [12]:
arr = np.ones(3)
arr

array([1., 1., 1.])

In [13]:
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr = np.ones((2,3), dtype=np.int16)
arr

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [15]:
arr7 = np.empty(3)
arr7

array([1., 1., 1.])

In [16]:
arr = np.empty((2,3), dtype=np.int16)
arr

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [21]:
arr = np.full(7, 54)
arr

array([54, 54, 54, 54, 54, 54, 54])

In [22]:
arr = np.full(7, 21.5)
arr

array([21.5, 21.5, 21.5, 21.5, 21.5, 21.5, 21.5])

In [23]:
arr = np.full((2,3), 21)
arr

array([[21, 21, 21],
       [21, 21, 21]])

In [24]:
eye_arr = np.eye(3,3)
eye_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
arr = np.fromstring('25 30 35 40', sep=' ')
arr

array([25., 30., 35., 40.])

In [26]:
import numpy as np
arr = np.arange(5)
print(arr)
print(type(arr))
print(arr.dtype)

[0 1 2 3 4]
<class 'numpy.ndarray'>
int64


In [28]:
arr = np.arange(5, 15, 1)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
arr = np.linspace(2,3,10)
print(arr)
print(arr.dtype)

[2.         2.11111111 2.22222222 2.33333333 2.44444444 2.55555556
 2.66666667 2.77777778 2.88888889 3.        ]
float64


In [30]:
#Python's built-in random module has random() function that returns a single float between 0 and 1
import numpy as np
value = np.random.rand()
value

0.8519279524488997

In [31]:
arr = np.random.rand(5)
arr

array([0.18320859, 0.46895537, 0.21252546, 0.707108  , 0.04896069])

In [32]:
arr = np.random.rand(5,4,3)
arr

array([[[0.99871901, 0.17337234, 0.85383659],
        [0.51659292, 0.55242993, 0.58946924],
        [0.73714826, 0.1916755 , 0.94517516],
        [0.68208267, 0.52502651, 0.84371471]],

       [[0.82151434, 0.94204541, 0.02695107],
        [0.12060998, 0.080965  , 0.88553719],
        [0.47321238, 0.88038789, 0.43917157],
        [0.30413073, 0.2645099 , 0.52591632]],

       [[0.98905932, 0.86832565, 0.31859926],
        [0.03526913, 0.86594947, 0.26074643],
        [0.45127874, 0.75761587, 0.90106531],
        [0.68420985, 0.34920028, 0.85206898]],

       [[0.79329572, 0.91346301, 0.45691556],
        [0.03937142, 0.75889009, 0.29997066],
        [0.49118686, 0.31745685, 0.80757614],
        [0.07629375, 0.22750071, 0.69123809]],

       [[0.32573257, 0.86424822, 0.79665617],
        [0.12875527, 0.16390287, 0.21088241],
        [0.67001953, 0.8755799 , 0.70781747],
        [0.59641493, 0.70398356, 0.34000969]]])

In [33]:
value = np.random.randint(10)
value

5

In [34]:
value = np.random.randint(low=5, high=20)
value

6

In [35]:
value = np.random.randint(low=-5, high=5)
value

-1

In [36]:
arr = np.random.randint(low = -5, high = 5, size = 4)
arr

array([4, 0, 3, 1], dtype=int32)

In [37]:
arr = np.random.randint(low = 1, high = 10, size = (2,3,4))
arr

array([[[5, 7, 8, 6],
        [7, 5, 6, 4],
        [6, 3, 9, 6]],

       [[7, 3, 9, 7],
        [9, 9, 5, 4],
        [1, 8, 6, 2]]], dtype=int32)

In [38]:
# creating a 2-D array
mylist = [[0, 1],[2, 3]]
arr1 = np.array(mylist)
print("A 2-D array \n", arr1)

# creating the same array as the shape of 'arr' filled with zeros
arr2 = np.zeros_like(arr1)
print("\n Converted Array \n", arr2)

A 2-D array 
 [[0 1]
 [2 3]]

 Converted Array 
 [[0 0]
 [0 0]]
